#! /bin/dash

# PATH="$PATH:$(pwd)"

# # create a temporary directory for the test.
# test_dir=$(mktemp -d)
# cd "$test_dir" || exit 1

# create a temporary directory for the test.
test_dir="dir_test"
mkdir "$test_dir"
cd "$test_dir" || exit 1

# create some files to hold output.

expected_output=$(mktemp)
actual_output=$(mktemp)

# remove the temporary directory when the test is done.

# trap 'rm "$expected_output" "$actual_output" -rf "$test_dir"' INT HUP QUIT TERM EXIT

# create pigs repository

pigs-init
echo 1 >a
echo 2 >b
echo 3 >c
pigs-add a b c
pigs-commit -m "first commit"
echo 4 >>a
echo 5 >>b
echo 6 >>c
echo 7 >d
echo 8 >e
pigs-add b c d
echo 9 >b
pigs-rm a
pigs-rm b 
pigs-rm c
pigs-rm d
pigs-rm e
pigs-rm --cached a